name: Gitea Action for checking typst compilation
run-name: Performing Typst compilation
on: [push]

jobs:
  run-ci-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Nix Shell
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run CI
        run: nix-shell --run ./run-ci.sh
