name: Build'n check
run-name: Performing Typst compilation
on:
  pull_request:
      types:
        - opened
        - synchronize
      branches:
        - main
jobs:
  run-ci-linux:
    runs-on: ubuntu-latest
    # run action mutally exclusive on PRs or
    # push with commit containing "Run-Checks"
    if: >
      (contains(github.event.head_commit.message, 'Run-Checks') &&
      github.event_name == 'push')
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies for Nix setup action
        run: |
          apt update -y
          apt install sudo -y
      - name: Setup Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Stylecheck
        run: nix-shell --run "./run-fmt.sh --check src/lib.typ"
      - id: build
        name: Build
        run: |
          nix-shell --run ./run-ci.sh
