name: Gitea Action for checking typst compilation
run-name: Performing Typst compilation
on: [push]

jobs:
  run-ci-linux:
    runs-on: ubuntu-latest
    env:
      TYPST_INSTALL: /usr/local
      TYPST_VERSION: 0.11.1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Typst CLI
        run: curl -fsSL https://typst.community/typst-install/install.sh | sh -s "$TYPST_VERSION"
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Run CI
        run: bash -c ./run-ci.sh
