name: Create Release Commit
on:
  push:
    branches:
      - main
    tags-ignore:
      - v*.*.*
jobs:
  prepare:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Release-As:')
    env:
      USERNAME: servostar
      EMAIL: sven.vogel123@web.de
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: 'main'
          token:  ${{ secrets.RELEASE_TOKEN }}
      - name: Tag Release Commit
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          GIT_AUTH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          export VERSION=$(echo "${COMMIT_MESSAGE}" | grep -Po '(?<=Release-As: )v\d+\.\d+\.\d+')
          git config --global user.name "${USERNAME}"
          git config --global user.email "${EMAIL}"
          echo "==> Update typst.toml version"
          sed -i "/version/c\version = \"${VERSION#v}\"" typst.toml
          git add typst.toml
          git commit -m "chore: bump release version to $VERSION"
          git push origin main
          echo "::endgroup::"
          echo "::group::{Tag commit}"
          git tag -m "Release" "${VERSION}"
          git push origin "${VERSION}"
          echo "::endgroup::"
