name: release

on: 
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Typst CLI
        run: curl -fsSL https://typst.community/typst-install/install.sh | sh -s "$TYPST_VERSION"
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Run CI
        run: bash -c ./run-ci.sh
      - name: Setup go
        uses: https://github.com/actions/setup-go@v4
        with:
          go-version: '>=1.20.1'
      - name: Create release  
        id: create-release
        uses: https://gitea.com/actions/release-action@main
        with:
          files: |-
            example.pdf
          api_key: '${{secrets.RELEASE_TOKEN}}'
