name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run CI
        run: nix-shell --run ./run-ci.sh
      - name: Setup go
        uses: https://github.com/actions/setup-go@v4
        with:
          go-version: '>=1.20.1'
      - name: Create release
        id: create-release
        uses: https://gitea.com/actions/release-action@main
        with:
          files: |-
            example.pdf
          api_key: '${{secrets.RELEASE_TOKEN}}'
